version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgis/postgis:latest
    container_name: beadando-db
    environment:
      POSTGRES_PASSWORD: "asdQWE123."
    ports:
      - "5469:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eddmeg

networks:
  eddmeg:
    driver: "bridge"

volumes:
  postgres-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /mnt/wwwdata/postgres-data
    #   o: bind